// Generated by jextract

package libpg_query.v15;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int stmt_location;
 *     int stmt_len;
 * }
 * }
 */
public class PgQuerySplitStmt {

    PgQuerySplitStmt() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        pg_query_h.C_INT.withName("stmt_location"),
        pg_query_h.C_INT.withName("stmt_len")
    ).withName("$anon$39:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt stmt_location$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stmt_location"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int stmt_location
     * }
     */
    public static final OfInt stmt_location$layout() {
        return stmt_location$LAYOUT;
    }

    private static final long stmt_location$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int stmt_location
     * }
     */
    public static final long stmt_location$offset() {
        return stmt_location$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int stmt_location
     * }
     */
    public static int stmt_location(MemorySegment struct) {
        return struct.get(stmt_location$LAYOUT, stmt_location$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int stmt_location
     * }
     */
    public static void stmt_location(MemorySegment struct, int fieldValue) {
        struct.set(stmt_location$LAYOUT, stmt_location$OFFSET, fieldValue);
    }

    private static final OfInt stmt_len$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stmt_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int stmt_len
     * }
     */
    public static final OfInt stmt_len$layout() {
        return stmt_len$LAYOUT;
    }

    private static final long stmt_len$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int stmt_len
     * }
     */
    public static final long stmt_len$offset() {
        return stmt_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int stmt_len
     * }
     */
    public static int stmt_len(MemorySegment struct) {
        return struct.get(stmt_len$LAYOUT, stmt_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int stmt_len
     * }
     */
    public static void stmt_len(MemorySegment struct, int fieldValue) {
        struct.set(stmt_len$LAYOUT, stmt_len$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

